### ISSUE TITLE
TWAS-aSPU: memory problem

### ISSUE THREAD

**Issue by eyu8** [ChongWu-Biostat/aSPU2#1]
Hello,
When trying to run TWAS, I encounter a 

 *** caught segfault ***
address 0x800000, cause 'memory not mapped'

I have the same problem when running your demo script in the ReadMe of this package.

This is my sessionInfo:
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2018.3.222/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] aSPU2_1.1        mvtnorm_1.0-11   MASS_7.3-51.4    bigmemory_4.5.33

loaded via a namespace (and not attached):
[1] bigmemory.sri_0.1.3 compiler_3.5.2      Rcpp_1.0.3

Any idea what might be the problem? Thank you.

**Comment by ChongWu-Biostat** [comment]
Sure. I will take a look. Thank you for reporting.

**Comment by ChongWu-Biostat** [comment]
I have tested it and it can be run smoothly in a server with the following versions: CentOS-7 and R 3.5.2. I wonder if you can reinstall the package to see if the problem has been solved.

**Comment by eyu8** [comment]
Reinstalling couldn't fix the problem. I sometimes have the 'memory not mapped' or 

error: arma::memory::acquire(): out of memory
*** Error in `/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx512/Compiler/gcc7.3/r/3.5.2/lib64/R/bin/exec/R': double free or corruption (!prev): 0x000000000156eab0 ***
I am using gcc/g++ 7.3.0

**Comment by ChongWu-Biostat** [comment]
aSPU involves a package called bigmemory, which is not very stable in the server. I have two questions:
1. Can you run the example codes without any problems?
2. If you rerun the problematic gene, can you get the result?

I will study more to see why we aSPU2 does not work.

**Comment by eyu8** [comment]
I tested it in TWAS and the example code of aSPU2 (shown below) and both have the same problem.
library(aSPU2)
n = 100
times <- 1:n
rho <- 0.3
sigma <- 2
H <- abs(outer(times, times, "-"))
V <- sigma * rho^H
p <- nrow(V)
V[cbind(1:p, 1:p)] <- V[cbind(1:p, 1:p)] * sigma
CovSsqrt<- t(eV$vectors %*% (t(eV$vectors) * sqrt(eV$values)))
U = CovSsqrt %*% rnorm(n)
weight = cbind(rep(1,100),runif(100))
aSPU(U,V,weight[,1],pow=c(1:6,Inf),n.perm = 10000)

I managed to pinpoint the error to this line: 
 Res = calcT0Wsim3(as.matrix(CovSsqrt), as.matrix(weight),as.matrix(pow),as.matrix(Ts.abs),T0s@address,n.perm)

However, as this function is compiled in C++, I was not able to go any further.

**Comment by ChongWu-Biostat** [comment]
It's a very wired problem. Do you install the dependency packages such as RcppArmadillo successfully? I have reinstalled the package aSPU2, and it works well in a Linux system centos 7.

**Comment by eyu8** [comment]
[bigmemory_log.txt](https://github.com/ChongWu-Biostat/aSPU2/files/3937385/bigmemory_log.txt)

This is the log for the installation of bigmemory. Do you also get warnings for deprecated classes when you install in R-3.5.2?
[aSPU2_log.txt](https://github.com/ChongWu-Biostat/aSPU2/files/3937389/aSPU2_log.txt)
This is the log for aSPU2. I get warnings for the same class as bigmemory. 
[RcppArmadillo_log.txt](https://github.com/ChongWu-Biostat/aSPU2/files/3937413/RcppArmadillo_log.txt)

I don't see any error when installing RcppArmadillo.

**Comment by eyu8** [comment]
Works when I compile with C++98.

**Comment by ChongWu-Biostat** [comment]
Sounds good. Can you share some details? I guess this issue is related to the dependent package, Rcpp.

Thank you for your help.

**Comment by eyu8** [comment]
From what I see, the warnings about auto-ptr class are related to the problem. After compiling bigmemory and aSPU2, I no longer get those warnings and everything work smoothly. I was wondering what compiler have you been using?

**Comment by ChongWu-Biostat** [comment]
Sorry for my late reply. I am not sure. I compile it on the server and never meet this problem. I will ask staffs to figure it out. Thank you for your help. Happy holidays!
